### ISSUE TITLE
osx librt

### ISSUE THREAD

**Issue by stuta** [ldrumm/chronos#9]
```luarocks install chronos``` fails on osx.
Mac OS X does not need (and does not have) the librt library.

**Comment by ldrumm** [comment]
On Wed, Nov 07, 2018 at 03:18:19AM -0800, stuta wrote:
> ```luarocks install chronos``` fails on osx.
> Mac OS X does not need (and does not have) the librt library. 
Regrettably Mac OS X is pretty much untested; I don't have access to
Apple hardware. My guess is that something like the following should
work:

diff --git a/update_rockspec.lua b/update_rockspec.lua
index 0c0c31b..57afdbc 100755
--- a/update_rockspec.lua
+++ b/update_rockspec.lua
@@ -35,6 +35,11 @@ rockspec = {
                     },
                 },
             },
+            macosx = {
+                modules = {
+                    chronos = "src/chronos.c",
+                }
+            },
         },
         type = "builtin",
         modules = {

Please test this and let me know if it's enough. If so, I'll push a new
version to luarocks.org

**Comment by stuta** [comment]
That works, thanks.

**Comment by ldrumm** [comment]
This is now available on luarocks.org. It should be available to install via luarocks install chronos. If there are issues or improvements for Mac OS X, please open a ticket or submit a patch.

Thanks
